baseURL = 'https://127local.net/'
languageCode = 'en-us'
title = '127local'

theme = 'xmin'

copyright = "Will Butler"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
        footer = "&copy; [Will Butler](https://whil.io) | [Github](https://github.com/whilb)"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/whilb"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
